### PR TITLE
big docs updates in README, implemented push/pop/shift/unshift

### PR DESCRIPTION
**Pull request by troygoode**

### CODE REVIEW

**Comment by troygoode** [comment]
@weepy: take a look at tonight's commits

**Comment by troygoode** [comment]
implemented o_O.array and o_O.list from issue #28

**Comment by weepy** [comment]
ok - I've merged. but I'm going to move o_O.list out into it's own file. It's much less useful than array - so I think makes sense as a 'plugin'.

Also we'll need to change how the binding works - since I think foreach will just append ?

**Comment by weepy** [comment]
I've outlined how I think we should change the renderOne.

**Pull request merged**
